### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by fengjiejiejiejie** [synlp/R2-LLM#1]
Hi, how can I get the paper? Is there an arXiv version ?

**Comment by AlonzoLeeeooo** [comment]
Hi @fengjiejiejiejie ,

Thank you for your attention! We are planning to upload an arXiv version of the accepted paper ASAP. And we will notice you as soon as the paper is available.

Best

**Comment by fengjiejiejiejie** [comment]
thanks a lot



---Original---
From: ***@***.***&gt;
Date: Sun, Jan 7, 2024 15:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [synlp/R2-LLM] Paper (Issue #1)




 
Hi @fengjiejiejiejie ,
 
Thank you for your attention! We are planning to upload an arXiv version of the accepted paper ASAP. And we notice you as soon as the paper is available.
 
Best

**Comment by AlonzoLeeeooo** [comment]
You can refer to the official version of our AAAI paper in [this website](https://ojs.aaai.org/index.php/AAAI/article/view/29826).
